# config/config.yaml
app:
  name: "NoDetours"
  version: "0.1.0"
  host: "127.0.0.1"
  port: 8000

llm:
  provider: "openai"  # or "anthropic"
  model: "gpt-3.5-turbo"  # Fast and reliable
  temperature: 0.7
  max_tokens: 4000

apis:
  weather:
    provider: "openweathermap"
    api_key: "${WEATHER_API_KEY}"
  maps:
    provider: "mock"
    api_key: "${MAPS_API_KEY}"